# Generated by Django 6.0 on 2025-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_producto_peso_por_bulto_producto_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='peso_bulto_kg',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo_kg',
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_por_bulto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg de un bulto (solo si aplica)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
