# Generated by Django 6.0 on 2026-01-07 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_remove_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadtransporte',
            name='marca',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidadtransporte',
            name='placa',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
