# Generated by Django 6.0 on 2026-01-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_remove_unidadtransporte_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
