# Generated by Django 6.0 on 2026-01-02 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_remove_producto_fecha_creacion_and_more'),
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='etapa',
            field=models.CharField(choices=[('pre_inicio', 'Pre-inicio'), ('iniciador', 'Iniciador'), ('crecimiento', 'Crecimiento'), ('desarrollo', 'Desarrollo'), ('engorda', 'Engorda'), ('gestacion', 'Gestación'), ('lactacion', 'Lactación')], max_length=20),
        ),
        migrations.RenameField(
            model_name='dieta',
            old_name='fecha_hora',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='dieta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieta',
            name='total_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='DetalleDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='dietas.dieta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
            ],
            options={
                'unique_together': {('dieta', 'producto')},
            },
        ),
        migrations.DeleteModel(
            name='DietaDetalle',
        ),
        migrations.DeleteModel(
            name='EtapaDieta',
        ),
    ]
