# Generated by Django 6.0 on 2026-01-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_remove_producto_fecha_creacion_and_more'),
        ('dietas', '0002_alter_dieta_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='producto_dieta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dieta', to='catalogos.producto'),
            preserve_default=False,
        ),
    ]
