# Generated by Django 6.0 on 2026-01-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0003_dieta_producto_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dieta',
            name='eliminada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
