# Generated by Django 6.0 on 2026-01-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0004_dieta_eliminada_dieta_eliminada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='fecha_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='preparada',
            field=models.BooleanField(default=False),
        ),
    ]
