# Generated by Django 6.0 on 2026-01-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0005_dieta_fecha_preparacion_dieta_preparada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='fecha_preparacion',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='preparada',
        ),
    ]
