# Generated by Django 6.0 on 2026-01-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0007_alter_dieta_options_preparaciondieta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dieta',
            options={},
        ),
    ]
