# Generated by Django 6.0 on 2025-12-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toneladas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bultos', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('TRASLADO', 'Traslado'), ('PEDIDO', 'Pedido')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toneladas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bultos', models.PositiveIntegerField(default=0)),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.chofer')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cliente')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.lugar')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.unidadtransporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
