# Generated by Django 6.0 on 2025-12-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('HUMEDAD', 'Humedad'), ('ROTURA', 'Rotura'), ('CADUCIDAD', 'Caducidad'), ('DERRAME', 'Derrame'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toneladas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bultos', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
