# Generated by Django 6.0 on 2026-01-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_remove_producto_fecha_creacion_and_more'),
        ('movimientos', '0002_merma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.proveedor'),
        ),
    ]
