# Generated by Django 6.0 on 2026-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_movimiento_movimientodetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('TRASLADO', 'Traslado'), ('PEDIDO', 'Pedido'), ('DIETA', 'Dieta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salida',
            name='tipo',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('TRASLADO', 'Traslado'), ('PEDIDO', 'Pedido'), ('DIETA', 'Dieta')], max_length=10),
        ),
    ]
